version: '3'

services:
  app:
    container_name: 'llama-llama-adventure'
    build: .
    volumes:
      - .:/home/node/llama-llama-adventure
      - ~/.bashrc:/home/node/.bashrc
      - ~/.bash_profile:/home/node/.bash_profile
      - ~/.gitconfig:/home/node/.gitconfig
    environment:
      - PLATFORM=docker
      - HOST=0.0.0.0
    ports:
      - '9000-9010:9000-9010'
    stdin_open: true
    tty: true
