version: '3'

services:
  app:
    container_name: 'llamallamaadventure'
    build: .
    volumes:
      - .:/home/node/llamallamaadventure
      - /home/llamallamaadventure/app/node_modules
    ports:
      - '3005:3005'
    stdin_open: true
    tty: true
